from pathlib import Path
p=Path('/home/ubuntu/pacca-vision/client/src/pages/Home.tsx')
s=p.read_text()
# Extend local types and solution shape.
s=s.replace('type Solution = { name: string; key: string; description: string; fields: SchemaField[]; color: string; Icon: LucideIcon };', 'type Version = { version: string; savedAt: string; author: string; note: string; fields: SchemaField[] };\n  type Solution = { name: string; key: string; description: string; fields: SchemaField[]; color: string; Icon: LucideIcon; versions: Version[] };')
s=s.replace('color: "#2478c7", Icon: FileText },', 'color: "#2478c7", Icon: FileText, versions: [{ version: "1.0", savedAt: "03 Sep 2026", author: "Solution Team", note: "Initial invoice output contract", fields: [{ name: "InvoiceNumber", type: "string", required: true, defaultValue: "" }, { name: "InvoiceDate", type: "date", required: true, defaultValue: "YYYY-MM-DD" }, { name: "VendorName", type: "string", required: true, defaultValue: "" }, { name: "TotalAmount", type: "number", required: true, defaultValue: "" }] }] },')
s=s.replace('color: "#8b5cf6", Icon: FileCheck2 },', 'color: "#8b5cf6", Icon: FileCheck2, versions: [{ version: "1.0", savedAt: "03 Sep 2026", author: "Solution Team", note: "Common patient and referral fields", fields: baseReferralFields.map((field) => ({ ...field })) }] },')
s=s.replace('color: "#0f9f83", Icon: Coins },', 'color: "#0f9f83", Icon: Coins, versions: [{ version: "1.0", savedAt: "03 Sep 2026", author: "Solution Team", note: "Initial payment output contract", fields: [{ name: "PaymentReference", type: "string", required: true, defaultValue: "" }, { name: "PaymentDate", type: "date", required: true, defaultValue: "YYYY-MM-DD" }, { name: "Amount", type: "number", required: true, defaultValue: "" }] }] },')
s=s.replace('color: "#64748b", Icon: FileCog };', 'color: "#64748b", Icon: FileCog, versions: [{ version: "1.0", savedAt: "03 Sep 2026", author: "Solution Team", note: "Default starter schema", fields: baseReferralFields.map((field) => ({ ...field })) }] };')
# Add state and callbacks after newField state.
s=s.replace('const [newField, setNewField] = useState("");', 'const [newField, setNewField] = useState("");\n  const [showHistory, setShowHistory] = useState(false);\n  const [sampleDocument, setSampleDocument] = useState("Referral fax sample\\nPatient: Jordan Lee\\nMember ID: M-20481\\nDOB: 1988-04-12\\nDate of service: 2026-09-03");\n  const [testResult, setTestResult] = useState<string | null>(null);')
# Update add draft already handled, updateSelected preserves versions.
# Add callbacks before schemaJson.
s=s.replace('const schemaJson = `{\\n${selected.fields.map', 'const saveConfiguration = () => { const nextVersion = (selected.versions.length + 1).toFixed(1); const version: Version = { version: nextVersion, savedAt: "03 Sep 2026", author: "Suresh Kiran", note: `Updated ${selected.fields.length} output fields and prompt`, fields: selected.fields.map((field) => ({ ...field })) }; updateSelected({ versions: [...selected.versions, version] }); setSaved(true); toast.success("Solution configuration saved", { description: `${selected.name} schema and prompt are ready for the pipeline.` }); };\n  const deleteSolution = (key: string) => { if (solutions.length === 1) { toast.error("At least one document type is required"); return; } const remaining = solutions.filter((item) => item.key !== key); setSolutions(remaining); if (selectedKey === key) setSelectedKey(remaining[0].key); toast("Document type deleted"); };\n  const runPrompt = () => { const output = Object.fromEntries(selected.fields.map((field) => [field.name, field.defaultValue])); setTestResult(JSON.stringify({ ...output, _test: { sampleDocument: sampleDocument.split("\\n")[0], status: "Prompt test completed", fieldsMapped: selected.fields.length } }, null, 2)); toast.success("Extraction test completed", { description: "Sample content was evaluated against the current prompt and schema." }); };\n  const exportConfiguration = () => { const payload = { documentType: selected.name, schemaKey: selected.key, fields: selected.fields, commonPrompt: prompt, generatedPrompt: promptWithSchema, exportedAt: new Date().toISOString() }; const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${selected.key.replace(/[^a-z0-9]+/gi, "-")}-configuration.json`; anchor.click(); URL.revokeObjectURL(url); toast.success("Configuration exported"); };\n  const schemaJson = `{\\n${selected.fields.map')
# Add delete button in each card after configured span.
s=s.replace('{selected.key === item.key ? "Editing" : "Configured"}</span></div></button>)}</aside>', '{selected.key === item.key ? "Editing" : "Configured"}</span></div><span onClick={(event) => { event.stopPropagation(); deleteSolution(item.key); }} role="button" tabIndex={0} className="mt-3 inline-flex items-center gap-1 text-[9px] font-bold text-slate-400 hover:text-rose-600"><Trash2 size={12} /> Delete</span></button>)}</aside>')
# Replace save button handler with callback and add export/history buttons.
s=s.replace('onClick={() => { setSaved(true); toast.success("Solution configuration saved", { description: `${selected.name} schema and prompt are ready for the pipeline.` }); }} className="inline-flex items-center gap-2 rounded-xl bg-[#156bc9]', 'onClick={saveConfiguration} className="inline-flex items-center gap-2 rounded-xl bg-[#156bc9]')
s=s.replace('<button onClick={saveConfiguration} className="inline-flex items-center gap-2 rounded-xl bg-[#156bc9] px-4 py-2.5 text-[10px] font-bold text-white"><Check size={14} /> Save configuration</button>', '<button onClick={() => setShowHistory(!showHistory)} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-[10px] font-bold text-slate-600"><HistoryIcon size={14} /> History ({selected.versions.length})</button><button onClick={exportConfiguration} className="inline-flex items-center gap-2 rounded-xl border border-blue-200 bg-blue-50 px-3 py-2.5 text-[10px] font-bold text-blue-700"><Download size={14} /> Export JSON</button><button onClick={saveConfiguration} className="inline-flex items-center gap-2 rounded-xl bg-[#156bc9] px-4 py-2.5 text-[10px] font-bold text-white"><Check size={14} /> Save configuration</button>')
# Add history panel and test-run panel before textarea.
s=s.replace('<textarea value={prompt}', '{showHistory && <div className="mt-5 rounded-xl border border-blue-100 bg-blue-50/50 p-4"><div className="flex items-center justify-between"><div><div className="text-[10px] font-bold text-[#142b4b]">Schema version history</div><div className="mt-1 text-[9px] text-slate-500">Each saved schema is retained for this document type.</div></div><span className="rounded-md bg-white px-2 py-1 text-[9px] font-bold text-blue-700">{selected.versions.length} versions</span></div><div className="mt-3 space-y-2">{[...selected.versions].reverse().map((version) => <div key={version.version} className="flex flex-wrap items-center gap-3 rounded-lg border border-blue-100 bg-white px-3 py-2"><span className="font-mono text-[10px] font-bold text-[#142b4b]">v{version.version}</span><span className="flex-1 text-[9px] text-slate-500">{version.note} · {version.author} · {version.savedAt}</span><button onClick={() => { updateSelected({ fields: version.fields.map((field) => ({ ...field })) }); toast("Schema version loaded", { description: `Loaded v${version.version} into the editor.` }); }} className="rounded-md border border-slate-200 px-2 py-1 text-[9px] font-bold text-slate-600">Load</button></div>)}</div></div>}<textarea value={prompt}')
# Add test panel before generated output grid.
s=s.replace('<div className="mt-4 grid gap-4 lg:grid-cols-2">', '<div className="mt-4 rounded-xl border border-violet-100 bg-violet-50/40 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="text-[10px] font-bold text-[#142b4b]">Test-run extraction prompt</div><div className="mt-1 text-[9px] text-slate-500">Paste sample document text to preview the current contract before connecting a pipeline.</div></div><button onClick={runPrompt} className="inline-flex items-center gap-1.5 rounded-lg bg-violet-600 px-3 py-2 text-[9px] font-bold text-white"><CirclePlay size={13} /> Run test</button></div><textarea value={sampleDocument} onChange={(e) => setSampleDocument(e.target.value)} className="mt-3 min-h-[90px] w-full rounded-lg border border-violet-100 bg-white p-3 font-mono text-[9px] text-slate-600 outline-none focus:border-violet-400" />{testResult && <pre className="mt-3 max-h-[180px] overflow-auto rounded-lg bg-[#142b4b] p-3 font-mono text-[9px] leading-relaxed text-violet-100">{testResult}</pre>}</div><div className="mt-4 grid gap-4 lg:grid-cols-2">')
p.write_text(s[:start]+s[start:end] if False else s)
print('extended Solutions')
