from pathlib import Path
p=Path('/home/ubuntu/pacca-vision/client/src/pages/Home.tsx')
s=p.read_text()
needle='</div></section>\\n  <section className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] font-bold uppercase tracking-[.14em] text-blue-600">Output schema'
insert='''</div><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="block"><span className="mb-1.5 block text-[9px] font-bold uppercase tracking-wider text-slate-400">What does this process do?</span><textarea value={selected.processDescription} onChange={(e) => updateSelected({ processDescription: e.target.value })} className="min-h-[76px] w-full rounded-xl border border-slate-200 p-3 text-[10px] leading-relaxed outline-none focus:border-blue-400" /></label><label className="block"><span className="mb-1.5 block text-[9px] font-bold uppercase tracking-wider text-slate-400">Model guidance for PDF/image</span><textarea value={selected.modelGuidance} onChange={(e) => updateSelected({ modelGuidance: e.target.value })} className="min-h-[76px] w-full rounded-xl border border-slate-200 p-3 text-[10px] leading-relaxed outline-none focus:border-blue-400" /></label></div></section>\n  <section className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] font-bold uppercase tracking-[.14em] text-blue-600">Output schema'''
if needle not in s:
    # use a less brittle anchor
    anchor='<section className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] font-bold uppercase tracking-[.14em] text-blue-600">Output schema'
    if anchor not in s: raise SystemExit('anchor missing')
    s=s.replace(anchor, '<section className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm sm:p-6"><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="block"><span className="mb-1.5 block text-[9px] font-bold uppercase tracking-wider text-slate-400">What does this process do?</span><textarea value={selected.processDescription} onChange={(e) => updateSelected({ processDescription: e.target.value })} className="min-h-[76px] w-full rounded-xl border border-slate-200 p-3 text-[10px] leading-relaxed outline-none focus:border-blue-400" /></label><label className="block"><span className="mb-1.5 block text-[9px] font-bold uppercase tracking-wider text-slate-400">Model guidance for PDF/image</span><textarea value={selected.modelGuidance} onChange={(e) => updateSelected({ modelGuidance: e.target.value })} className="min-h-[76px] w-full rounded-xl border border-slate-200 p-3 text-[10px] leading-relaxed outline-none focus:border-blue-400" /></label></div><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] font-bold uppercase tracking-[.14em] text-blue-600">Output schema', 1)
else:
    s=s.replace(needle, insert, 1)
p.write_text(s)
print('guidance inserted')
