from pathlib import Path
p=Path('/home/ubuntu/pacca-vision/client/src/pages/Home.tsx')
s=p.read_text()
s=s.replace('const [fieldValues, setFieldValues] = useState({ invoiceNumber: "INV-2026-002", invoiceDate: "29-Aug-2026", vendorName: "Global Office Supplies", purchaseOrder: "PO-45822", subtotal: "₹42,000", taxAmount: "₹7,560", totalAmount: "₹49,560", currency: "INR", dueDate: "28-Sep-2026" });\n  const editableFields', 'const initialFieldValues = { invoiceNumber: "INV-2026-002", invoiceDate: "29-Aug-2026", vendorName: "Global Office Supplies", purchaseOrder: "PO-45822", subtotal: "₹42,000", taxAmount: "₹7,560", totalAmount: "₹49,560", currency: "INR", dueDate: "28-Sep-2026" };\n  const [fieldValues, setFieldValues] = useState(initialFieldValues);\n  const [changedFields, setChangedFields] = useState<string[]>([]);\n  const editableFields')
s=s.replace('setFieldValues({ ...fieldValues, [key]: e.target.value }); if (key === "totalAmount") setTotalAmount(e.target.value); setSaved(false); setResolved(false);', 'setFieldValues({ ...fieldValues, [key]: e.target.value }); if (key === "totalAmount") setTotalAmount(e.target.value); setChangedFields(changedFields.includes(key) ? changedFields : [...changedFields, key]); setSaved(false); setResolved(false);')
needle='<label className="block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[.08em] text-slate-400">Reviewer note</span>'
insert='<div className="rounded-xl border border-blue-100 bg-blue-50/50 p-4"><div className="flex items-center justify-between"><div><div className="text-[11px] font-bold text-[#142b4b]">Reviewer change summary</div><div className="mt-1 text-[10px] text-slate-500">Audit preview for this HIL correction draft</div></div><span className="rounded-full bg-white px-2 py-1 text-[9px] font-bold text-blue-700">{changedFields.length} changed</span></div>{changedFields.length === 0 ? <div className="mt-3 rounded-lg border border-dashed border-blue-200 bg-white/70 p-3 text-[10px] text-slate-400">No field changes yet. Corrections will appear here with original and revised values.</div> : <div className="mt-3 space-y-2">{changedFields.map((key) => { const label = editableFields.find((field) => field[1] === key)?.[0] ?? key; return <div key={key} className="grid grid-cols-[1fr_auto_1fr] items-center gap-2 rounded-lg bg-white p-2.5 text-[10px]"><div><div className="text-[9px] font-bold text-slate-400">{label}</div><div className="mt-0.5 truncate text-slate-400 line-through">{initialFieldValues[key as keyof typeof initialFieldValues]}</div></div><ArrowRight size={13} className="text-blue-400" /><div><div className="text-[9px] font-bold text-blue-600">Revised</div><div className="mt-0.5 truncate font-semibold text-[#142b4b]">{fieldValues[key as keyof typeof fieldValues]}</div></div></div>})}</div>}</div>'+needle
if needle not in s: raise SystemExit('reviewer note location not found')
s=s.replace(needle,insert)
s=s.replace('setSaved(true); toast.success("Changes saved", { description: "All invoice field corrections saved to the review draft." });', 'setSaved(true); toast.success("Changes saved", { description: `${changedFields.length} reviewer field change${changedFields.length === 1 ? "" : "s"} recorded in the audit summary.` });')
p.write_text(s)
print('HIL audit summary added')
