from pathlib import Path
p=Path('/home/ubuntu/pacca-vision/client/src/pages/Home.tsx')
s=p.read_text()
s=s.replace('const [totalAmount, setTotalAmount] = useState("₹49,560");\n  const item', 'const [totalAmount, setTotalAmount] = useState("₹49,560");\n  const [fieldValues, setFieldValues] = useState({ invoiceNumber: "INV-2026-002", invoiceDate: "29-Aug-2026", vendorName: "Global Office Supplies", purchaseOrder: "PO-45822", subtotal: "₹42,000", taxAmount: "₹7,560", totalAmount: "₹49,560", currency: "INR", dueDate: "28-Sep-2026" });\n  const editableFields = [["Invoice Number", "invoiceNumber"], ["Invoice Date", "invoiceDate"], ["Vendor Name", "vendorName"], ["Purchase Order", "purchaseOrder"], ["Subtotal", "subtotal"], ["Tax Amount", "taxAmount"], ["Total Amount", "totalAmount"], ["Currency", "currency"], ["Due Date", "dueDate"]];\n  const item')
s=s.replace('setTotalAmount(e.target.value); setSaved(false); setResolved(false);', 'setTotalAmount(e.target.value); setFieldValues({ ...fieldValues, totalAmount: e.target.value }); setSaved(false); setResolved(false);')
old='<label className="block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[.08em] text-slate-400">Total Amount · flagged field</span><input value={totalAmount} onChange={(e) => { setTotalAmount(e.target.value); setFieldValues({ ...fieldValues, totalAmount: e.target.value }); setSaved(false); setResolved(false); }} className="h-10 w-full rounded-xl border border-amber-300 bg-amber-50/30 px-3 text-[11px] font-semibold text-slate-700 outline-none focus:border-blue-500" /></label><label className="block">'
new='<div><div className="mb-2 flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[.08em] text-slate-400">Editable extracted metadata</span><span className="text-[9px] font-semibold text-amber-600">HIL review document only</span></div><div className="grid gap-3 sm:grid-cols-2">{editableFields.map(([label, key]) => <label key={key} className="block"><span className="mb-1.5 block text-[9px] font-bold text-slate-500">{label}{key === "totalAmount" && " · flagged"}</span><input value={fieldValues[key]} onChange={(e) => { setFieldValues({ ...fieldValues, [key]: e.target.value }); if (key === "totalAmount") setTotalAmount(e.target.value); setSaved(false); setResolved(false); }} className={cn("h-9 w-full rounded-lg border px-2.5 text-[10px] font-semibold text-slate-700 outline-none focus:border-blue-500", key === "totalAmount" ? "border-amber-300 bg-amber-50/30" : "border-slate-200 bg-white")} /></label>)}</div></div><label className="block">'
if old not in s: raise SystemExit('HIL total amount control not found')
s=s.replace(old,new)
s=s.replace('Total Amount correction saved to the review draft.', 'All invoice field corrections saved to the review draft.')
p.write_text(s)
print('HIL all-field editor added')
