from pathlib import Path
home=Path('/home/ubuntu/pacca-vision/client/src/pages/Home.tsx')
auth=Path('/home/ubuntu/pacca-vision/client/src/components/MockAuth.tsx')
s=home.read_text()
s=s.replace('const [selectedNodeIndex, setSelectedNodeIndex] = useState(0);\n  const nodes =','const [selectedNodeIndex, setSelectedNodeIndex] = useState(0);\n  const [connectorSaved, setConnectorSaved] = useState(true);\n  const [connectorConfig, setConnectorConfig] = useState({ inputConnector: "Amazon S3", inputIntegration: "Client 1 — Invoice Intake", inputBucket: "client-1-invoices", inputPath: "/incoming/", outputConnector: "Amazon S3", outputIntegration: "Client 1 — Invoice Output", outputBucket: "client-1-output", outputPath: "/processed/" });\n  const nodes =')
s=s.replace('const visibleSections = navSections.map((section) => ({ ...section, items: section.items.filter((item) => allowedPaths.includes(item.path)) })).filter((section) => section.items.length > 0);','const DEMO_HIDDEN_PATHS = ["/deployment", "/infrastructure"];\n  const visibleSections = navSections.map((section) => ({ ...section, items: section.items.filter((item) => allowedPaths.includes(item.path) && !DEMO_HIDDEN_PATHS.includes(item.path)) })).filter((section) => section.items.length > 0);')
s=s.replace('Client 1 <ChevronDown size={13} className="text-slate-500" />','Client 1 <span className="rounded-md bg-white/8 px-1.5 py-0.5 text-[8px] font-bold uppercase tracking-wider text-slate-500">Authorized</span>')
s=s.replace('["Invoice Processing", "Apply confidence checks, tax validation, and HIL review when required.", "5 metadata fields", "#0d9f9c", Coins],\n  ["Invoice Processing", "Deliver validated invoice metadata to downstream payable workflows.", "30s target SLA", "#8b5ac7", Send],','["Referral Creation", "Classify referral documents and route complete referral packets for review.", "Conditional HIL", "#0d9f9c", Coins],\n  ["Payment Posting", "Validate remittance details and deliver posting-ready metadata downstream.", "30s target SLA", "#8b5ac7", Send],')
old='<div className="mt-3 space-y-2.5 text-[10px]"><div className="flex items-center justify-between"><span className="text-slate-400">{selectedNodeIndex === 0 ? "Connector" : "Output connector"}</span><span className="font-semibold text-[#142b4b]">Amazon S3</span></div><div className="flex items-center justify-between gap-3"><span className="text-slate-400">Integration</span><span className="text-right font-semibold text-[#142b4b]">Client 1 — {selectedNodeIndex === 0 ? "Invoice Intake" : "Invoice Output"}</span></div><div className="flex items-center justify-between"><span className="text-slate-400">Bucket</span><span className="font-mono font-semibold text-[#142b4b]">{selectedNodeIndex === 0 ? "client-1-invoices" : "client-1-output"}</span></div><div className="flex items-center justify-between"><span className="text-slate-400">Path</span><span className="font-mono font-semibold text-[#142b4b]">{selectedNodeIndex === 0 ? "/incoming/" : "/processed/"}</span></div></div></div>}'
new='<div className="mt-3 space-y-2.5 text-[10px]">{(selectedNodeIndex === 0 ? [["Connector", "inputConnector"], ["Integration", "inputIntegration"], ["Bucket", "inputBucket"], ["Path", "inputPath"]] : [["Output connector", "outputConnector"], ["Integration", "outputIntegration"], ["Bucket", "outputBucket"], ["Path", "outputPath"]]).map(([label, key]) => <label key={key} className="block"><span className="mb-1 block text-slate-400">{label}</span><input value={connectorConfig[key]} onChange={(e) => { setConnectorConfig({ ...connectorConfig, [key]: e.target.value }); setConnectorSaved(false); }} className="h-8 w-full rounded-lg border border-blue-100 bg-white px-2.5 font-mono text-[10px] font-semibold text-[#142b4b] outline-none focus:border-blue-400" /></label>)}<button onClick={() => { setConnectorSaved(true); toast.success("Connector changes saved"); }} className={cn("mt-1 inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-[9px] font-bold", connectorSaved ? "bg-emerald-50 text-emerald-700" : "bg-blue-600 text-white")}>{connectorSaved ? "Saved" : "Save connector changes"}</button></div></div>}'
if old not in s: raise SystemExit('connector block not found')
s=s.replace(old,new)
home.write_text(s)
a=auth.read_text()
old_auth='<label className="block"><span className="mb-2 block text-[10px] font-bold text-slate-500">{entryMode === "central" ? "Platform scope" : "Workspace / tenant"}</span><select disabled={entryMode === "central"} value={entryMode === "central" ? "PACCA Platform" : tenant} onChange={(e) => setTenant(e.target.value)} className="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-[11px] font-semibold text-slate-700 outline-none focus:border-blue-500">{entryMode === "central" ? <option>PACCA Platform</option> : <option>Client 1</option>}</select></label>'
new_auth='<div className="block"><span className="mb-2 block text-[10px] font-bold text-slate-500">{entryMode === "central" ? "Platform scope" : "Authorized workspace"}</span><div className="flex h-11 items-center justify-between rounded-xl border border-slate-200 bg-slate-50 px-3 text-[11px] font-semibold text-slate-700"><span>{entryMode === "central" ? "PACCA Platform" : "Client 1"}</span><span className="text-[9px] font-bold text-emerald-600">Authorized</span></div></div>'
if old_auth not in a: raise SystemExit('auth selector not found')
a=a.replace(old_auth,new_auth)
auth.write_text(a)
print('demo cleanup patch applied')
