from pathlib import Path
p=Path('/home/ubuntu/pacca-vision/client/src/pages/Home.tsx')
s=p.read_text()
# Add process metadata to the solution model.
s=s.replace('type Solution = { name: string; key: string; description: string; fields: SchemaField[]; color: string; Icon: LucideIcon; versions: Version[] };', 'type Solution = { name: string; key: string; description: string; processDescription: string; modelGuidance: string; prompt: string; fields: SchemaField[]; color: string; Icon: LucideIcon; versions: Version[] };')
# Add default process/prompt data after baseReferralFields.
needle='  const [solutions, setSolutions] = useState<Solution[]>(['
insert='''  const genericPrompt = `You are a precise document extraction assistant. Extract the requested business metadata from the document and return one valid JSON object — nothing else.\n\nPROCESS DESCRIPTION:\n{{PROCESS_DESCRIPTION}}\n\nMODEL GUIDANCE:\n{{MODEL_GUIDANCE}}\n\nReturn ONLY a valid JSON object with the configured output fields.`;\n  const referralPrompt = `You are a precise medical document parser specializing in fax referral documents. Extract structured patient, provider, and referral metadata and return one valid JSON object — nothing else.\n\nDATE FORMATTING:\n- All dates → "YYYY-MM-DD" format regardless of how they appear\n\nPATIENT NAME:\n- Format PatientName as "LastName FirstName" and split first and last names separately\n\nIDs:\n- Extract Member ID and Subscriber ID with care; if not found return "Not Found"\n\nReturn ONLY a valid JSON object with the configured output fields.`;\n  const invoicePrompt = `You are Invoice Extractor, a precise financial document parser. Extract invoice header, vendor, amount, tax, currency, purchase order, and due-date metadata from the invoice.\n\nDATE FORMATTING:\n- All dates → "YYYY-MM-DD" format\n\nAMOUNTS:\n- Return numeric amount fields without currency symbols when the schema type is number\n\nReturn ONLY a valid JSON object with the configured output fields.`;\n  const paymentPrompt = `You are Payment Posting Extractor, a precise remittance and payment document parser. Extract payment reference, posting date, payer, amount, currency, and reconciliation metadata.\n\nDATE FORMATTING:\n- All dates → "YYYY-MM-DD" format\n\nRECONCILIATION:\n- Preserve source references exactly and return "Not Found" when a critical identifier is absent\n\nReturn ONLY a valid JSON object with the configured output fields.`;\n'''
s=s.replace(needle,insert+needle)
# Add fields to initial solutions after descriptions.
s=s.replace('description: "Extract invoice metadata, validate totals, and deliver trusted financial records.", fields:', 'description: "Extract invoice metadata, validate totals, and deliver trusted financial records.", processDescription: "Turn supplier invoices into validated financial metadata for downstream accounts payable workflows.", modelGuidance: "Use the invoice layout, table rows, totals block, and tax labels as primary evidence. Do not infer missing amounts.", prompt: invoicePrompt, fields:')
s=s.replace('description: "Create a structured referral record from fax and referral documents.", fields:', 'description: "Create a structured referral record from fax and referral documents.", processDescription: "Turn fax referrals and medical intake documents into a normalized patient and referral record.", modelGuidance: "Prioritize fax headers, patient demographics, payer/member identifiers, dates of service, and form indicators. Preserve critical IDs exactly.", prompt: referralPrompt, fields:')
s=s.replace('description: "Normalize payment remittances and post validated transactions downstream.", fields:', 'description: "Normalize payment remittances and post validated transactions downstream.", processDescription: "Normalize payment and remittance documents into trusted posting records for reconciliation.", modelGuidance: "Use remittance tables, payment references, payer information, dates, and adjustment lines. Never manufacture a payment amount.", prompt: paymentPrompt, fields:')
s=s.replace('description: "Define a new document-processing requirement and output contract.", fields:', 'description: "Define a new document-processing requirement and output contract.", processDescription: "Describe what this new document type represents and which downstream business process consumes it.", modelGuidance: "Explain which PDF or image regions the model should prioritize and what it must never infer.", prompt: genericPrompt, fields:')
# Replace prompt state with upload state and retain editable prompt synchronized from selected.
s=s.replace('const [sampleDocument, setSampleDocument] = useState("Referral fax sample\\nPatient: Jordan Lee\\nMember ID: M-20481\\nDOB: 1988-04-12\\nDate of service: 2026-09-03");\n  const [testResult, setTestResult] = useState<string | null>(null);', 'const [sampleDocument, setSampleDocument] = useState("Referral fax sample\\nPatient: Jordan Lee\\nMember ID: M-20481\\nDOB: 1988-04-12\\nDate of service: 2026-09-03");\n  const [sampleFile, setSampleFile] = useState<File | null>(null);\n  const [samplePreview, setSamplePreview] = useState<string | null>(null);\n  const [testResult, setTestResult] = useState<string | null>(null);')
# Selection helper and prompt synchronization.
s=s.replace('const updateSelected = (changes: Partial<Solution>) => {', 'const selectSolution = (key: string) => { const next = solutions.find((item) => item.key === key); if (next) { setSelectedKey(key); setSampleFile(null); setSamplePreview(null); setTestResult(null); } };\n  const updateSelected = (changes: Partial<Solution>) => {')
s=s.replace('onClick={() => setSelectedKey(key)}', 'onClick={() => selectSolution(key)}')
s=s.replace('setSelectedKey(key); setSaved(false); toast("Document type added"', 'setSelectedKey(key); setSaved(false); toast("Document type added"')
# Make prompt generated content include process-specific guidance.
s=s.replace('const schemaJson = `{\\n${selected.fields.map', 'const effectivePrompt = selected.prompt.replace("{{PROCESS_DESCRIPTION}}", selected.processDescription).replace("{{MODEL_GUIDANCE}}", selected.modelGuidance);\n  const promptWithSchema = `${effectivePrompt}\\n\\nOUTPUT SCHEMA:\\n${schemaJson}`;\n  const schemaJson = `{\\n${selected.fields.map')
# Remove old duplicate promptWithSchema if present after replacement.
s=s.replace('  const promptWithSchema = `${prompt}\\n\\nOUTPUT SCHEMA:', '  const promptWithSchema = `${effectivePrompt}\\n\\nOUTPUT SCHEMA:')
# Save prompt with current editor text: use effective prompt state via selected.prompt (the textarea now directly edits it).
s=s.replace('commonPrompt: prompt, generatedPrompt:', 'commonPrompt: selected.prompt, generatedPrompt:')
# Add file upload handler and include file info in test.
s=s.replace('const runPrompt = () => { const output = Object.fromEntries', 'const handleSampleFile = (file: File | undefined) => { if (!file) return; const allowed = file.type === "application/pdf" || file.type.startsWith("image/"); if (!allowed) { toast.error("Upload a PDF or image file"); return; } setSampleFile(file); setSamplePreview(file.type.startsWith("image/") ? URL.createObjectURL(file) : null); setTestResult(null); };\n  const runPrompt = () => { const output = Object.fromEntries')
s=s.replace('sampleDocument: sampleDocument.split("\\n")[0], status:', 'sampleDocument: sampleFile ? sampleFile.name : sampleDocument.split("\\n")[0], status:')
# Add process and model fields after document type inputs.
s=s.replace('</div></section>\\n  <section className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] font-bold uppercase tracking-[.14em] text-blue-600">Output schema', '</div><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="block"><span className="mb-1.5 block text-[9px] font-bold uppercase tracking-wider text-slate-400">What does this process do?</span><textarea value={selected.processDescription} onChange={(e) => updateSelected({ processDescription: e.target.value })} className="min-h-[76px] w-full rounded-xl border border-slate-200 p-3 text-[10px] leading-relaxed outline-none focus:border-blue-400" /></label><label className="block"><span className="mb-1.5 block text-[9px] font-bold uppercase tracking-wider text-slate-400">Model guidance for PDF/image</span><textarea value={selected.modelGuidance} onChange={(e) => updateSelected({ modelGuidance: e.target.value })} className="min-h-[76px] w-full rounded-xl border border-slate-200 p-3 text-[10px] leading-relaxed outline-none focus:border-blue-400" /></label></div></section>\n  <section className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] font-bold uppercase tracking-[.14em] text-blue-600">Output schema')
# Prompt textarea uses selected.prompt and updates selected.
s=s.replace('<textarea value={prompt} onChange={(e) => { setPrompt(e.target.value); setSaved(false); }}', '<textarea value={selected.prompt} onChange={(e) => { updateSelected({ prompt: e.target.value }); setSaved(false); }}')
# Add upload UI before sample text textarea.
s=s.replace('<textarea value={sampleDocument} onChange={(e) => setSampleDocument(e.target.value)} className="mt-3 min-h-[90px]', '<label className="mt-3 flex cursor-pointer items-center justify-between gap-3 rounded-lg border border-dashed border-violet-200 bg-white px-3 py-2.5"><span className="flex items-center gap-2 text-[9px] font-semibold text-slate-600"><Upload size={14} className="text-violet-600" /> {sampleFile ? sampleFile.name : "Upload a sample PDF or image"}</span><input type="file" accept="application/pdf,image/*" onChange={(e) => handleSampleFile(e.target.files?.[0])} className="hidden" /></label>{samplePreview && <img src={samplePreview} alt="Uploaded sample preview" className="mt-3 max-h-[180px] rounded-lg border border-violet-100 object-contain" />}<textarea value={sampleDocument} onChange={(e) => setSampleDocument(e.target.value)} className="mt-3 min-h-[90px]')
p.write_text(s)
print('prompt/upload patch applied')
