import type { DocumentDetail } from "./api";

export const DEMO_HIL_DOC: DocumentDetail = {
  summary: {
    documentId: "demo-pa-88421",
    file: "PA-88421_Dupixent_ClinicalExceptions.pdf",
    docType: "prior_authorization",
    status: "needs_review",
    uiStatus: "Needs Review",
    confidence: 0.64,
    needsReview: true,
    reviewReasons: ["ocr_needs_review", "ungrounded", "extraction_needs_review"],
    reviewFields: ["prescriber_npi", "patient_dob", "member_id"],
    pages: 2,
    fieldCount: 8,
    fieldsNeedingReview: 3,
    costUsd: 0.042,
    latencyMs: 1850,
    minPageConfidence: 0.54,
    receivedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    source: "Upload Modal (Intake Portal)",
    reviewStatus: "needs_review",
    reviewedBy: null,
    claimedBy: null,
    correctionCount: 0,
  },
  ocr: {
    pageCount: 2,
    engine: "Azure Document Intelligence 4.0",
    minConfidence: 0.54,
  },
  extract: {
    model: "claude-3-5-sonnet",
    promptTokens: 3420,
    completionTokens: 610,
  },
  pdfUrl: null,
  outreach: {
    visible: true,
    enabled: true,
    skipReason: null,
    openCount: 1,
    patientAskableOpen: 0,
    blankRequiredCount: 0,
    gapStatus: "pending",
    callDirection: "outbound",
    hasGapsItem: true,
  },
  review: {
    status: "needs_review",
    corrections: {},
    audit: [],
    claimed_by: null,
    reviewed_by: null,
    reviewed_at: null,
    note: null,
  },
  fields: {
    docType: "prior_authorization",
    fields: {
      prescriber_npi: {
        value: "1942850193",
        quote: null,
        class: "A",
        needs_review: true,
        review_reasons: ["ungrounded"],
        scores: {
          model_confidence: 0.70,
          grounding_score: 0.32,
          ocr_score: 0.95,
          field_score: 0.32,
          weakest_signal: "grounding",
        },
        grounding: {
          grounded: false,
          quote_in_document: false,
          page: 2,
        },
      },
      patient_dob: {
        value: "04/12/1984",
        quote: "DOB: 04/12/1984",
        class: "A",
        needs_review: true,
        review_reasons: ["ocr_needs_review", "low_ocr_confidence"],
        scores: {
          model_confidence: 0.65,
          grounding_score: 0.90,
          ocr_score: 0.54,
          field_score: 0.54,
          weakest_signal: "ocr",
        },
        grounding: {
          grounded: true,
          ocr_confidence: 0.54,
          page: 1,
        },
      },
      member_id: {
        value: "W98340127",
        quote: "Member ID: W98340127",
        class: "A",
        needs_review: true,
        review_reasons: ["extraction_needs_review", "low_model_confidence"],
        scores: {
          model_confidence: 0.68,
          grounding_score: 0.72,
          ocr_score: 0.74,
          field_score: 0.68,
          weakest_signal: "model_confidence",
        },
        grounding: {
          grounded: true,
          ocr_confidence: 0.74,
          page: 1,
        },
      },
      patient_name: {
        value: "Johnathan R. Davis",
        quote: "Patient Name: Johnathan R. Davis",
        class: "A",
        needs_review: false,
        scores: {
          model_confidence: 0.99,
          grounding_score: 0.99,
          ocr_score: 0.98,
          field_score: 0.99,
        },
        grounding: {
          grounded: true,
          ocr_confidence: 0.98,
          page: 1,
        },
      },
      medication: {
        value: "Dupixent 300mg/2mL",
        quote: "Requested Medication: Dupixent 300mg/2mL Pre-filled Syringe",
        class: "A",
        needs_review: false,
        scores: {
          model_confidence: 0.98,
          grounding_score: 0.97,
          ocr_score: 0.96,
          field_score: 0.97,
        },
        grounding: {
          grounded: true,
          ocr_confidence: 0.96,
          page: 1,
        },
      },
      diagnosis: {
        value: "L20.9 Atopic Dermatitis",
        quote: "Primary Diagnosis: L20.9 Atopic Dermatitis, severe refractory",
        class: "B",
        needs_review: false,
        scores: {
          model_confidence: 0.96,
          grounding_score: 0.95,
          ocr_score: 0.94,
          field_score: 0.95,
        },
        grounding: {
          grounded: true,
          ocr_confidence: 0.94,
          page: 1,
        },
      },
      prescriber_name: {
        value: "Dr. Sarah Jenkins, MD",
        quote: "Attending Prescriber: Dr. Sarah Jenkins, MD",
        class: "A",
        needs_review: false,
        scores: {
          model_confidence: 0.97,
          grounding_score: 0.96,
          ocr_score: 0.95,
          field_score: 0.96,
        },
        grounding: {
          grounded: true,
          ocr_confidence: 0.95,
          page: 2,
        },
      },
      patient_phone: {
        value: "(555) 382-9104",
        provenance: {
          origin: "ivr",
          askedAs: "Could you confirm the best callback number for patient?",
          by: "IVR Outreach Bot",
          at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        },
        needs_review: false,
        scores: {
          field_score: 0.99,
        },
      },
    },
  },
};
